### ISSUE TITLE
Is this repository incomplete and abandoned?

### ISSUE THREAD

**Issue by shelby-carter** [travis-ci/travis-styleguide#1]
Really can't see a lot of elements from original travis-web UI. 

Just wanted to know if there's going to be any progress on this or is there a more complete version anywhere in public access? 

Thanks

**Comment by lislis** [comment]
Hey @joykeeper! Sorry for the long wait... 
The styleguide project in _this_ form has been abandoned. It was our first shot at the whole topic trying one possible technical solution.
We might publish a styleguide some time this year with a different setup and probably in a different repo. But there is no ETA for this project.

**Comment by shelby-carter** [comment]
@lislis thanks for the reply! I hope the new one will be published :)
